### ISSUE TITLE
Error when error argument missing

### ISSUE THREAD

**Issue by DaMaillard** [keleshev/schema#121]
Error when serialazing a SchemaError object : 

```python
>>> import copy
>>> from schema import SchemaError
>>> s = SchemaError('a', None)
>>> copy.deepcopy(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/damienmaillard/.virtualenvs/bricklane/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/damienmaillard/.virtualenvs/bricklane/lib/python3.4/copy.py", line 295, in _reconstruct
    y = callable(*args)
TypeError: __init__() missing 1 required positional argument: 'errors'
```

**Comment by DaMaillard** [comment]
@skorokithakis Can you please update PyPI ?

**Comment by skorokithakis** [comment]
Sure!

**Comment by skorokithakis** [comment]
https://pypi.python.org/pypi/schema/0.6.3
