### ISSUE TITLE
way to validate dependency between keys?

### ISSUE THREAD

**Issue by mkj28** [keleshev/schema#164]
Can we validate a dictionary like this:
```
[{'name': 'Sue', 'age': 28},
 {'name': 'Max', 'dob': '2000-01-01'}]
```
either age or dob must be provided, but if one is provided, the other should not exist.

**Comment by kurtbrose** [comment]
you can use a callback to add functionality that isn't provided by builtins

```python
def age_or_dob(data):
   return ('age' in data and 'dob' not in data) or ('age' not in data and 'dob' in data)

s = Schema([And({'name': str, Optional('age'): int, Optional('dob'): str}, age_or_dob)])
s.validate([{'name': 'Sue', 'age': 28}, {'name': 'Max', 'dob': '2000-01-01', 'age': 7}])
'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/schema.py", line 243, in validate
    return type(data)(o.validate(d) for d in data)
  File "/usr/local/lib/python2.7/site-packages/schema.py", line 243, in <genexpr>
    return type(data)(o.validate(d) for d in data)
  File "/usr/local/lib/python2.7/site-packages/schema.py", line 120, in validate
    x.errors)
schema.SchemaError: Or(And({Optional('dob'): <type 'str'>, Optional('age'): <type 'int'>, 'name': <type 'str'>}, <function age_or_dob at 0x7f6e7d543500>)) did not validate {'dob': '2000-01-01', 'age': 7, 'name': 'Max'}
'''
age_or_dob({'dob': '2000-01-01', 'age': 7, 'name': 'Max'}) should evaluate to True
s.validate([{'name': 'Sue', 'age': 28}, {'name': 'Max', 'dob': '2000-01-01'}])

# [{'age': 28, 'name': 'Sue'}, {'dob': '2000-01-01', 'name': 'Max'}]
```

**Comment by mkj28** [comment]
Awesome, thanks @kurtbrose

**Comment by kdebrab** [comment]
One could also use the schema:

```python
s = Schema([{'name': str, 'dob': str},
            {'name': str, 'age': int}])
```

**Comment by kurtbrose** [comment]
oh yea, that approach is much clearer and more concise
