### ISSUE TITLE
Wrong use of "key '' is required" exception

### ISSUE THREAD

**Issue by charlax** [keleshev/schema#25]
Hey,

It seems that the exception raised line https://github.com/halst/schema/blob/master/schema.py#L139 can also be raised when there's no handler for a given dict key.

Code to reproduce the problem:

```python
schema.Schema({schema.Optional("toaster"): basestring}).validate({"grillepain": None})
```

This will raise `SchemaError: key Optional('toaster') is required`.

**Comment by sjakobi** [comment]
```python
>>> schema.Schema({schema.Optional("toaster"): basestring}).validate({"grillepain": None})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "schema.py", line 153, in validate
    e)
schema.SchemaError: Wrong keys 'grillepain' in {'grillepain': None}
```

Seems to be fixed.
