### ISSUE TITLE
Bug: TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by sammorley-short** [keleshev/schema#253]
I am finding a bug when validating the schema `{(): [(str,)]}`. 

Here's the repro:

```python
from schema import Schema

schema = Schema({
    (): [(str,)]
})
data = {(): ['foo', ('bar',)]}
schema.is_valid(data)
```

which produces the following error:

```
Traceback (most recent call last):
  File "/Users/.../python3.7/site-packages/schema.py", line 396, in validate
    nvalue = Schema(svalue, error=e, ignore_extra_keys=i).validate(value)
  File "/Users/.../python3.7/site-packages/schema.py", line 357, in validate
    return type(data)(o.validate(d) for d in data)
  File "/Users/.../python3.7/site-packages/schema.py", line 357, in <genexpr>
    return type(data)(o.validate(d) for d in data)
  File "/Users/.../python3.7/site-packages/schema.py", line 167, in validate
    [self._error.format(data) if self._error else None] + errors,
schema.SchemaError: Or((<class 'str'>,)) did not validate 'foo'
'foo' should be instance of 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    schema.is_valid(data)
  File "/Users/.../python3.7/site-packages/schema.py", line 329, in is_valid
    self.validate(data)
  File "/Users/.../python3.7/site-packages/schema.py", line 398, in validate
    k = "Key '%s' error:" % nkey
TypeError: not enough arguments for format string
```

Seems like some sort of string substitution error, so should probably be pretty easy to fix.

**Comment by ljluestc** [comment]
from schema import Schema

class FixedSchema(Schema):
    def _validate(self, data, update=False):
        errors = []
        try:
            if not update:
                data = self.validator(data)
            for o in self._iterable(data):
                try:
                    if not self._check(o):
                        raise self._error([self._error.format(data) if self._error else None])
                except SchemaError as e:
                    errors += e.errors
        except SchemaError as e:
            errors += e.errors
        if errors:
            raise self._error + errors

schema = FixedSchema({
    (): [(str,)]
})
data = {(): ['foo', ('bar',)]}
schema.is_valid(data)
