### ISSUE TITLE
Weird validation error message with inner dictionary

### ISSUE THREAD

**Issue by asteinlein** [keleshev/schema#38]
I might very well be misunderstanding something, but I don't get why the following doesn't work:

``` python
import json
from schema import Schema, And, Use
schema = Schema({
    'session_type': And(len, Use(str.lower), lambda s: s in ('newsletter',)),
    'user_ip': And(len, str),
    'options': {
        'skip_recipients_step': bool
    }
})
schema.validate(json.loads("""
{
  "session_type": "newsletter",
  "user_ip": "127.0.0.1",
  "options": {
    "skip_foo_bar": true,
    "skip_recipients_step": true
  }
}
"""
))
```

This gives these errors:

```
schema.SchemaError: key 'options' is required
key 'skip_recipients_step' is required
```

Just validating `options` with `And(dict, len)` works just fine, so the key is obviously there. But how can validate the contents of the nested dictionaries?

**Comment by sjakobi** [comment]
Running @asteinlein's original example with the current master (e94b7144f3016654d1360eb1c070fd2db0d54a43):

```
$ python3.4 issue38.py 
Traceback (most recent call last):
  File "issue38.py", line 19, in <module>
    """
  File "/home/simon/src/schema/schema.py", line 130, in validate
    nvalue = Schema(svalue, error=e).validate(value)
  File "/home/simon/src/schema/schema.py", line 153, in validate
    e)
schema.SchemaError: Wrong keys 'skip_foo_bar' in {'skip_recipients_step': True, 'skip_foo_bar': True}
```

Does this resolve the issue, @asteinlein?
