### ISSUE TITLE
Created Is validator, is it useful for creating a PR?

### ISSUE THREAD

**Issue by gabrielhpugliese** [keleshev/schema#60]
The motivation is setting different error message on SchemaError when trying to validate a single type.

This is the code:
```python
class Is(And):
    def __init__(self, *args, **kwargs):
        super(Is, self).__init__(*args, **kwargs)
        self._type = args[0]

    def validate(self, data):
        if not isinstance(data, self._type):
            error_message = '{} did not validate {}'.format(
                repr(self),
                repr(data)
            )
            raise SchemaError(error_message, error_message)
        return True
```

And usage:
```python
SCHEMA = Schema({
    'number': Is(int, error='Invalid zipcode param'),
})
```

Should I create a PR?

**Comment by keleshev** [comment]
How about this:

```python
>>> import schema
>>> schema.Schema(int, error='Invalid zipcode param').validate('hai')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/schema.py", line 161, in validate
    raise SchemaError('%r should be instance of %r' % (data, s), e)
schema.SchemaError: Invalid zipcode param
```

**Comment by gabrielhpugliese** [comment]
Yes, it does! Thank you!
