### ISSUE TITLE
Cannot install with pip3 -- README.rst contains non-ascii character.

### ISSUE THREAD

**Issue by Grazfather** [keleshev/schema#68]
```bash
$ pip3 install schema
Downloading/unpacking schema
  Downloading schema-0.3.1.tar.gz
  Running setup.py (path:/private/tmp/pip_build_bla/schema/setup.py) egg_info for package schema
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_bla/schema/setup.py", line 16, in <module>
        long_description=open('README.rst').read(),
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_bla/schema/setup.py", line 16, in <module>

    long_description=open('README.rst').read(),

  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_bla/schema
Storing debug log for failure in /Users/bla/.pip/pip.log
```

The culprit line in the readme is here:

```
Alternatively, you can just drop `schema.py` file into your project—it is self-contained.
```
(The m-width dash)

If I set LANG=utf-8, it works:

```bash
$ LANG=utf-8 pip install schema
Downloading/unpacking schema
  Downloading schema-0.3.1.tar.gz
  Running setup.py (path:/Users/bla/tmpvenv/build/schema/setup.py) egg_info for package schema

Installing collected packages: schema
  Running setup.py install for schema

Successfully installed schema
Cleaning up...
```

**Comment by Grazfather** [comment]
You could just remove that character, or modify setup.py:

`open('README.rst', encoding='utf8').read()`

**Comment by Grazfather** [comment]
The above is python3 only. To make it work on both we need to use `codecs`. I fixed my PR.
